apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story-app
  template:
    metadata:
      labels:
        app: story-app
    spec:
      containers:
        - name: story
          image: pavanbhat99/kub-story:1
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
          env:
            - name: STORY_FOLDER
              value: "story"
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
