apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
        - name: first-app
          image: pavanbhat99/kub-first-app:2
