apiVersion: v1
kind: Service
metadata:
  name: first-app-deployment-service
spec:
  selector:
    app: first-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
    #   for more ports we do it like this
    # - protocol: "TCP"
    #   port: 3000
    #   targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
        - name: first-app
          image: pavanbhat99/kub-first-app:2
